AWSTemplateFormatVersion: '2010-09-09'
Description: 'GitProfile Lambda deployment with CloudFront'

Parameters:
  S3Bucket:
    Type: String
    Description: S3 bucket containing the Lambda deployment package
  S3Key:
    Type: String
    Description: S3 key for the Lambda deployment package

Resources:
  # Lambda Execution Role
  LambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole

  # Lambda Function
  GitProfileLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: gitprofile-function
      Runtime: nodejs18.x
      Handler: index.handler
      Code:
        S3Bucket: !Ref S3Bucket
        S3Key: !Ref S3Key
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 30
      MemorySize: 512

  # Lambda Function URL
  GitProfileFunctionUrl:
    Type: AWS::Lambda::Url
    Properties:
      TargetFunctionArn: !Ref GitProfileLambda
      AuthType: NONE
      Cors:
        AllowCredentials: false
        AllowHeaders:
          - '*'
        AllowMethods:
          - GET
          - POST
        AllowOrigins:
          - '*'

  # Permission for Function URL
  GitProfileFunctionUrlPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref GitProfileLambda
      Action: lambda:InvokeFunctionUrl
      Principal: '*'
      FunctionUrlAuthType: NONE

Outputs:
  LambdaFunctionUrl:
    Description: 'Lambda Function URL'
    Value: !GetAtt GitProfileFunctionUrl.FunctionUrl
  LambdaFunctionArn:
    Description: 'Lambda Function ARN'
    Value: !GetAtt GitProfileLambda.Arn